# Generated by Django 3.2.5 on 2021-08-25 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('coverImageSrc', models.ImageField(default='images/empty.jpg', upload_to='images/')),
            ],
            options={
                'ordering': ['startDate', 'endDate'],
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('zIndex', models.IntegerField(default=1)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('coverImageSrc', models.ImageField(default='images/empty.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('src', models.ImageField(default='images/empty.jpg', upload_to='images/')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.landmark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandmarkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.landmark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('src', models.ImageField(default='images/empty.jpg', upload_to='images/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='map.content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='map.landmark'),
        ),
    ]
