# Generated by Django 3.2.6 on 2021-09-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210903_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landmarkcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarkComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmarkcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contentimage',
            name='owner',
        ),
        migrations.AddField(
            model_name='contentimage',
            name='owner',
            field=models.ManyToManyField(related_name='contentImages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='landmarkimage',
            name='owner',
        ),
        migrations.AddField(
            model_name='landmarkimage',
            name='owner',
            field=models.ManyToManyField(related_name='landmarkImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
