# Generated by Django 4.1.2 on 2022-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_content_link_alter_content_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name_eng',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='landmark',
            name='name_eng',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='landmark',
            name='price',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
