# Generated by Django 4.1.2 on 2022-10-23 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_content_name_eng_content_price_landmark_name_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='map.landmark')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarkReports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='map.content')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentReports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='landmarkreport',
            constraint=models.UniqueConstraint(fields=('owner', 'landmark'), name='unique_owner_landmark_report'),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(fields=('owner', 'content'), name='unique_owner_content_report'),
        ),
    ]
