# Generated by Django 3.2.6 on 2021-09-03 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210903_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentComments', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.RemoveField(
            model_name='contentimage',
            name='owner',
        ),
        migrations.AddField(
            model_name='contentimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='map.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmarkcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarkComments', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.RemoveField(
            model_name='landmarkimage',
            name='owner',
        ),
        migrations.AddField(
            model_name='landmarkimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarkImages', to='map.customuser'),
            preserve_default=False,
        ),
    ]
