# Generated by Django 4.1 on 2022-10-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_customuser_is_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landmark', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
