# Generated by Django 4.1 on 2022-10-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_landmark_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landmarkcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarkComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contentcomment',
            constraint=models.UniqueConstraint(fields=('owner', 'content'), name='unique_owner_content_comment'),
        ),
        migrations.AddConstraint(
            model_name='landmarkcomment',
            constraint=models.UniqueConstraint(fields=('owner', 'landmark'), name='unique_owner_landmark_comment'),
        ),
    ]
