# Generated by Django 4.1 on 2022-10-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_contentcomment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentImages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landmarkimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarkImages', to=settings.AUTH_USER_MODEL),
        ),
    ]
