# Generated by Django 4.1.2 on 2022-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_content_owner_alter_contentimage_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
