# Generated by Django 4.1.2 on 2022-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_content_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
    ]
