# Generated by Django 4.1.2 on 2022-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_alter_content_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landmark',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
